-- MySQL Script generated by MySQL Workbench
-- Sun Apr 24 05:02:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `email` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(20) NULL,
  UNIQUE INDEX `mdpClient_UNIQUE` (`Password` ASC) VISIBLE,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `id` VARCHAR(20) NOT NULL,
  `nom` VARCHAR(100) NULL,
  `stock` INT NULL,
  `invalide` VARCHAR(20) NULL,
  `price` DOUBLE NULL,
  `photo` VARCHAR(1000) NULL,
  `categorie` VARCHAR(50) NULL,
  `promo` VARCHAR(20) NULL,
  `interface` INT NULL,
  `desc` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`panier` (
  `idp` VARCHAR(20) NOT NULL,
  `idc` VARCHAR(20) NOT NULL,
  `quantite` INT NULL,
  PRIMARY KEY (`idc`, `idp`),
  INDEX `idProduit_idx` (`idp` ASC) VISIBLE,
  CONSTRAINT `idp`
    FOREIGN KEY (`idp`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idc`
    FOREIGN KEY (`idc`)
    REFERENCES `mydb`.`client` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `id` VARCHAR(11) NOT NULL,
  `nom` VARCHAR(20) NULL,
  `carnet` VARCHAR(20) NULL,
  `date_debut` DATE NULL,
  `date_fin` DATE NULL,
  `photo` VARCHAR(100) NULL,
  `clent` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `idc_idx` (`clent` ASC) VISIBLE,
  CONSTRAINT `client`
    FOREIGN KEY (`clent`)
    REFERENCES `mydb`.`client` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`abonnement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`abonnement` (
  `id` VARCHAR(20) NOT NULL,
  `email` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `email_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `email`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`client` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
