-- MySQL Script generated by MySQL Workbench
-- Sun Mar 20 20:34:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `idclient` VARCHAR(45) NOT NULL,
  `nomClient` VARCHAR(45) NULL,
  `prenomClient` VARCHAR(45) NULL,
  `emailClient` VARCHAR(45) NULL,
  `mdpClient` VARCHAR(45) NULL,
  PRIMARY KEY (`idclient`),
  UNIQUE INDEX `mdpClient_UNIQUE` (`mdpClient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `idproduit` VARCHAR(45) NOT NULL,
  `nomProduit` VARCHAR(45) NULL,
  `stockProduit` INT NULL,
  `categorieProduit` VARCHAR(45) NULL,
  `prixProduit` DOUBLE NULL,
  PRIMARY KEY (`idproduit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`panier` (
  `idpanier` VARCHAR(45) NOT NULL,
  `quantité` INT NULL,
  `idClient` VARCHAR(45) NULL,
  `idProduit` VARCHAR(45) NULL,
  PRIMARY KEY (`idpanier`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  INDEX `idPoduit_idx` (`idProduit` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPoduit`
    FOREIGN KEY (`idProduit`)
    REFERENCES `mydb`.`produit` (`idproduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facture` (
  `idfacture` VARCHAR(45) NOT NULL,
  `prixTotal` DOUBLE NULL,
  `idClient` VARCHAR(45) NULL,
  `idProduit` VARCHAR(45) NULL,
  PRIMARY KEY (`idfacture`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  INDEX `idProduit_idx` (`idProduit` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProduit`
    FOREIGN KEY (`idProduit`)
    REFERENCES `mydb`.`produit` (`idproduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`animal` (
  `idanimal` VARCHAR(45) NOT NULL,
  `nomAnimal` VARCHAR(45) NULL,
  `dateArrivee` DATE NULL,
  `dateSortie` DATE NULL,
  `carnetAnimal` VARCHAR(45) NULL,
  `idClient` VARCHAR(45) NULL,
  PRIMARY KEY (`idanimal`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avis` (
  `idAvis` VARCHAR(45) NOT NULL,
  `Etoile` VARCHAR(45) NULL,
  `commentaire` VARCHAR(45) NULL,
  `idClient` VARCHAR(45) NULL,
  PRIMARY KEY (`idAvis`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reclamation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reclamation` (
  `idreclamation` VARCHAR(45) NOT NULL,
  `commentaire` VARCHAR(45) NULL,
  `idClient` VARCHAR(45) NULL,
  PRIMARY KEY (`idreclamation`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
